export enum ErrorCode {
  NOT_PAIRED = "NOT_PAIRED",
  AUTH_FAILED = "AUTH_FAILED",
  PERMISSION_DENIED = "PERMISSION_DENIED",
  TAB_NOT_FOUND = "TAB_NOT_FOUND",
  ELEMENT_NOT_FOUND = "ELEMENT_NOT_FOUND",
  TAB_LEASED_BY_OTHER_SESSION = "TAB_LEASED_BY_OTHER_SESSION",
  COMMAND_TIMEOUT = "COMMAND_TIMEOUT",
  INTERNAL_ERROR = "INTERNAL_ERROR",
  INVALID_PARAMS = "INVALID_PARAMS",
}
